name: DDC with variable inputs
run-name: ${{ github.actor }} is testing out DDC with variable inputs 🚀
on: 
  workflow_dispatch:
    inputs:
      upload-results:
        type: boolean
        default: false
        description: Upload all ddc binary artifacts as an archive?
      compromise-tcc:
        type: boolean
        default: false
        description: Compromise grand parent tcc?
      init-script:
        type: string
        default: ".github/workflows/scripts/init.sh"
        description: "Script for setting up compilers for DDC"

jobs:
  DDC:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - name: Setup tcc
        run: nix-shell --run "./.github/workflows/scripts/setup.sh $( [[ "${{ inputs.compromise-tcc }}" == 'true' ]] && echo "-c" )"
      - name: Perform DDC
        run: nix-shell --run "./.github/workflows/scripts/ddc.sh -e ubuntu-24.04 -i ${{ inputs.init-script }}"
      - name: Upload hashes
        id: upload_hashes  
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-24.04.txt
          path: /tmp/build/ubuntu-24.04.txt
      - name: Create tar
        if: ${{ github.event.inputs.upload-results == 'true' }}
        run: tar -czf ./build-ubuntu-24.04.tar.gz ./build
      - name: Upload results
        if: ${{ github.event.inputs.upload-results == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: ./build-ubuntu-24.04.tar.gz
          name: build-ubuntu-24.04.tar.gz
  
  summary:
    runs-on: ubuntu-latest
    needs: [DDC]
    steps:
      - uses: actions/checkout@v4
      - name: Fetch hashes
        uses: actions/download-artifact@v4
        with:
          path: hashes
          pattern: ubuntu-*
          merge-multiple: true
      - run: |
          ls hashes
          cat hashes/*