name: DDC with variable inputs
run-name: ${{ github.actor }} is testing out DDC with variable inputs 🚀
on: 
  workflow_dispatch:
    inputs:
      compromise-tcc:
        type: boolean
        default: false
        description: Compromise grand parent tcc?
      init-script:
        type: string
        default: ".github/workflows/scripts/init.sh"
        description: "Script for setting up compilers for DDC"

jobs:
  DDC:
    strategy:
        matrix:
            os: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - name: Setup tcc
        run: nix-shell --pure --run "./.github/workflows/scripts/setup.sh $( [[ "${{ inputs.compromise-tcc }}" == 'true' ]] && echo "-c" )"
      - name: Perform DDC
        run: nix-shell --pure --run "./.github/workflows/scripts/ddc.sh -e ${{ matrix.os }} -i ${{ inputs.init-script }}"
      - name: Upload hashes
        id: upload_hashes
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}.txt
          path: /tmp/build/${{ matrix.os }}.txt
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: /tmp/build
          name: build-${{ matrix.os }}
  
  summary:
    runs-on: ubuntu-24.04
    needs: [DDC]
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: build-artifacts
          pattern: build-*
          merge-multiple: true
      - run: |
          ls build-artifacts