name: DDC for tcc
run-name: ${{ github.actor }} is testing out DDC for tcc 🚀
on: 
  workflow_dispatch:
    inputs:
      upload-results:
        type: boolean
        default: false
        description: Upload all ddc binary artifacts as an archive?
      compromise-tcc:
        type: boolean
        default: false
        description: Compromise grand parent tcc?

jobs:
  DDC:
    strategy:
        matrix:
          os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Debug output
        run: |
            gcc -v
            gcc --print-file-name=crtbegin.o
            ar V
            echo "kernel: $(uname -r)"
      - name: Setup tcc
        run: ./.github/workflows/scripts/setup.sh $( [[ "${{ inputs.compromise-tcc }}" == 'true' ]] && echo "-c" )
      - name: Perform DDC
        run: ./.github/workflows/scripts/ddc.sh -e ${{ matrix.os }}
      - name: Upload hashes
        id: upload_hashes  
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}.txt
          path: /tmp/build/${{ matrix.os }}.txt
      - name: Create tar
        if: ${{ github.event.inputs.upload-results == 'true' }}
        run: tar -czf ./build-${{matrix.os}}.tar.gz ./build
      - name: Upload results
        if: ${{ github.event.inputs.upload-results == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: ./build-${{matrix.os}}.tar.gz
          name: build-${{matrix.os}}.tar.gz
  
  summary:
    runs-on: ubuntu-latest
    needs: [DDC]
    steps:
      - uses: actions/checkout@v4
      - name: Fetch hashes
        uses: actions/download-artifact@v4
        with:
          path: hashes
          pattern: ubuntu-*
          merge-multiple: true
      - run: |
          ls hashes
          cat hashes/*