name: DDC with variable inputs
run-name: ${{ github.actor }} is testing out DDC with variable inputs 🚀
on: 
  workflow_dispatch:
    inputs:
      compromise-tcc:
        type: boolean
        default: false
        description: Compromise grand parent tcc?
      tcc-commit-hash:
        type: string
        default: "f6385c05308f715bdd2c06336801193a21d69b50"
        description: "Commit hash from https://repo.or.cz/tinycc.git to use as input source in DDC"
      nixpkgs-rev:
        type: string
        default: "a9eb3eed170fa916e0a8364e5227ee661af76fde"
        description: "Nixpkgs hash"

jobs:
  DDC:
    strategy:
        matrix:
            os: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16
      - name: Setup tcc
        run: nix-shell --argstr pkgs-rev ${{ inputs.nixpkgs-rev }} --pure --run "./.github/workflows/scripts/setup.sh $( [[ "${{ inputs.compromise-tcc }}" == 'true' ]] && echo "-c" )"
      - name: Perform DDC
        run: nix-shell --argstr pkgs-rev ${{ inputs.nixpkgs-rev }} --pure --run "./.github/workflows/scripts/ddc.sh -e ${{ matrix.os }} -h ${{ inputs.tcc-commit-hash }}"
      - name: Upload build
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          if-no-files-found: error
          path: /tmp/build
          name: build-${{ matrix.os }}
  
  Results:
    runs-on: ubuntu-24.04
    needs: [DDC]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Download build artifacts
        uses: actions/download-artifact@b14cf4c92620c250e1c074ab0a5800e37df86765 # v4.2.0
        with:
          path: build-artifacts
          pattern: build-*
      - name: Create summary
        run: ./.github/workflows/scripts/summary.sh ${{ inputs.tcc-commit-hash }}
  
  Release:
    runs-on: ubuntu-24.04
    needs: [Results]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/download-artifact@b14cf4c92620c250e1c074ab0a5800e37df86765 # v4.2.0
        with:
          path: build-artifacts
          pattern: build-*
      - name: debug
        run: |
          ls -la build-artifacts
          ls -la build-artifacts/build-ubuntu-24.04
      - name: Generate version
        id: ver
        run: |
          chmod +x ./build-artifacts/build-ubuntu-24.04/tcc-stage2/usr/bin/tcc
          echo "CURRENT_RELEASE=$(./build-artifacts/build-ubuntu-24.04/tcc-stage2/usr/bin/tcc -v | awk '{print $3}')+git$(echo ${{ inputs.tcc-commit-hash }} | cut -c1-8)" >> $GITHUB_OUTPUT
      - name: Create .deb archive
        run: sudo ./.github/workflows/scripts/deb-packaging/build-deb.sh -d build-artifacts/build-ubuntu-24.04/tcc-stage2 -v ${{ steps.ver.outputs.CURRENT_RELEASE }}
      - name: Upload .deb
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          if-no-files-found: error
          path: /tmp/tcc-hardened_${{ steps.ver.outputs.CURRENT_RELEASE }}.deb
          name: tcc-hardened_${{ steps.ver.outputs.CURRENT_RELEASE }}.deb
      - name: Create release
        run: |
          gh release create ${{ steps.ver.outputs.CURRENT_RELEASE }} --notes "test"
          gh release upload ${{ steps.ver.outputs.CURRENT_RELEASE }} /tmp/tcc-hardened_${{ steps.ver.outputs.CURRENT_RELEASE }}.deb


