name: DDC with variable inputs
run-name: ${{ github.actor }} is testing out DDC with variable inputs 🚀
on: 
  workflow_dispatch:
    inputs:
      compromise-tcc:
        type: boolean
        default: false
        description: Compromise grand parent tcc?
      tcc-commit-hash:
        type: string
        default: "f6385c05308f715bdd2c06336801193a21d69b50"
        description: "Commit hash from https://repo.or.cz/tinycc.git to use as input source in DDC"
      nixpkgs-rev:
        type: string
        default: "a9eb3eed170fa916e0a8364e5227ee661af76fde"
        description: "Nixpkgs hash"

jobs:
  DDC:
    strategy:
        matrix:
            os: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - name: Setup tcc
        run: nix-shell --argstr pkgs-rev ${{ inputs.nixpkgs-rev }} --pure --run "./.github/workflows/scripts/setup.sh $( [[ "${{ inputs.compromise-tcc }}" == 'true' ]] && echo "-c" )"
      - name: Perform DDC
        run: nix-shell --argstr pkgs-rev ${{ inputs.nixpkgs-rev }} --pure --run "./.github/workflows/scripts/ddc.sh -e ${{ matrix.os }} -h ${{ inputs.tcc-commit-hash }}"
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: /tmp/build
          name: build-${{ matrix.os }}
  
  Results:
    runs-on: ubuntu-24.04
    needs: [DDC]
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: build-artifacts
          pattern: build-*
      - name: Create summary
        run: ./.github/workflows/scripts/summary.sh ${{ inputs.tcc-commit-hash }}
  
  Release:
    runs-on: ubuntu-24.04
    needs: [Results]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: build-artifacts
          pattern: build-*
      - name: debug
        run: |
          ls -la build-artifacts
          ls -la build-artifacts/build-ubuntu-24.04
      - name: Create .deb archive
        run: ./.github/workflows/scripts/build-deb.sh -d build-artifacts/build-ubuntu-24.04/tcc-stage2
      - name: Upload .deb
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: /tmp/tcc-hardened.deb
          name: tcc-hardened.deb
